production:
  redis_url: <%= ENV['REDIS_URL'] %>
  redis_pool:
    size: 5
    timeout: 5
development:
  redis_url: redis://127.0.0.1:8877/1
  redis_pool:
    size: 5
    timeout: 5
test:
  redis_url: redis://127.0.0.1:8877/2
  redis_pool:
    size: 5
    timeout: 5